### ISSUE TITLE
TLS with selfsigned certificate

### ISSUE THREAD

**Issue by mreiger** [fluent-plugins-nursery/fluent-plugin-remote_syslog#44]
Hi I am trying to use this plugin (via the [fluentd kubernetes daemonset](https://github.com/fluent/fluentd-kubernetes-daemonset) [Debian syslog docker image](https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/v1.12/debian-syslog), which as far as I can tell uses this plugin for output.)

I need to use TLS encryption and the syslog receiver uses a selfsigned certificate. Therefore I tried to disable certificate verification with the verify_mode paramter; however I still get a verification error and no connection.

This is my output configuration:
```
  <label @OUTPUT>
    <match **>
      @type remote_syslog
      host "syslogserver"
      port 12555
      protocol tcp
      tls true
      verify_mode 0
      packet_size 65535
      <buffer>
        retry_max_interval 300
      </buffer>
      <format>
        @type "json"
      </format>
    </match>
  </label>
```
Name matching is done via /etc/hosts (through Kubernetes hostAliases) entry.

The selfsigned certificate has "syslogserver" both as issuer and subject CN; but this should not matter since I try to disable certificate verification anyway.

The error message I get is:
```
2021-06-11 17:41:49 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2021-06-11 17:41:50 +0000 chunk="5c48105438fdcf12caab52270b36345b" error_class=RuntimeError error="verification error"
  2021-06-11 17:41:49 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/remote_syslog_sender-1.2.1/lib/remote_syslog_sender/tcp_sender.rb:73:in `block in connect'
  2021-06-11 17:41:49 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/remote_syslog_sender-1.2.1/lib/remote_syslog_sender/tcp_sender.rb:52:in `synchronize'
  2021-06-11 17:41:49 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/remote_syslog_sender-1.2.1/lib/remote_syslog_sender/tcp_sender.rb:52:in `connect'
  2021-06-11 17:41:49 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/remote_syslog_sender-1.2.1/lib/remote_syslog_sender/tcp_sender.rb:38:in `initialize'
  2021-06-11 17:41:49 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-remote_syslog-1.0.0/lib/fluent/plugin/out_remote_syslog.rb:136:in `new'
  2021-06-11 17:41:49 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-remote_syslog-1.0.0/lib/fluent/plugin/out_remote_syslog.rb:136:in `create_sender'
  2021-06-11 17:41:49 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-remote_syslog-1.0.0/lib/fluent/plugin/out_remote_syslog.rb:91:in `write'
  2021-06-11 17:41:49 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2021-06-11 17:41:49 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2021-06-11 17:41:49 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2021-06-11 17:41:49 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

I also tried other values for verify_mode after some searching:
* none
* OpenSSL::SSL::VERIFY_NONE

but the result - and the error message - is the same.

Can you advise me what the correct use of the parameter is?

**Comment by mreiger** [comment]
Update: Using the selfsigned certificate as CA certificate (Parameter ca_file) works.

Still, it is not clear to me how the verify_mode parameter is supposed to work. Can anyone clarify?

**Comment by satish-suradkar** [comment]
Hi @mreiger

**Comment by satish-suradkar** [comment]
Hi @mreiger 

I have cerated self signed CA certificate. Created Server certificate and signed that with the CA.

Syslog server config ->
```
$ModLoad imtcp
$InputTCPServerRun 1514
$InputTCPServerStreamDriverMode 1 # run driver in TLS-only mode
$InputTCPServerStreamDriverAuthMode anon

#Make gtls driver the default
$DefaultNetstreamDriver gtls
# certificate files
#
$DefaultNetstreamDriverCAFile /etc/rsyslog-keys/ca.pem
$DefaultNetstreamDriverCertFile /etc/rsyslog-keys/server-cert.pem
$DefaultNetstreamDriverKeyFile /etc/rsyslog-keys/server-key.pem

```

Fluentd COnfig
```

<match *.*>
         @type remote_syslog
         host <syslogsrver-hostname>
         port 1514
         protocol tcp
         tls true
         ca_file /etc/rsyslog-keys-my-ss/ca.pem
  </match>

```
getting err -->
```

2022-05-25 12:45:24 +0000 [warn]: #0 failed to flush the buffer. retry_time=11 next_retry_seconds=2022-05-25 13:04:30 +0000 chunk="5dfd52f20e6fd2d95309fb4f32b59316" error_class=RuntimeError error="verification error"
 2022-05-25 12:45:24 +0000 [warn]: #0 suppressed same stacktrace
2022-05-25 13:04:34 +0000 [warn]: #0 failed to flush the buffer. retry_time=12 next_retry_seconds=2022-05-25 13:41:59 +0000 chunk="5dfd52f20e6fd2d95309fb4f32b59316" error_class=RuntimeError error="verification error"
 2022-05-25 13:04:34 +0000 [warn]: #0 suppressed same stacktrace

```

Could you please suggest what i'm missing?

**Comment by vara2504** [comment]
@mreiger @satish-suradkar 

i am facing an issue while using this plugin enabling TLS  option with "StreamDriver.Authmode="x509/certvalid" .

I have created a self signed certificate which works perfectly for rsyslog client to rsyslog server with "x509/certvalid" mode. but not when i pass the ca.pem via fluentd. these are my configurations.

rsyslog server configuration:
```
module(load="imtcp"
        StreamDriver.Name="gtls"
        StreamDriver.Mode="1"
        StreamDriver.Authmode="x509/certvalid"
        gnutlsprioritystring="SECURE128:-VERS-TLS-ALL:+VERS-TLS1.3"
)
input(type="imtcp" port="6514")

$DefaultNetstreamDriver gtls
$DefaultNetstreamDriverCAFile /etc/rsyslog-cert/ca.pem
$DefaultNetstreamDriverCertFile /etc/rsyslog-cert/server-cert.pem
$DefaultNetstreamDriverKeyFile /etc/rsyslog-cert/server-key.pem

``` 
```
Fluentd config:
 <store>
      @type "remote_syslog"
      host "hostname"
      port 6514
      packet_size 1024
      protocol tcp
      tls true
      ca_file "/etc/fluentd/syslogpath/ca.pem"
      severity "debug"
      hostname "hostname"
      <format>
        @type "json"
      </format>
      <buffer>
        flush_mode interval
        flush_interval 5s
      </buffer>
    </store>
```
could you guys please let me know if i am missing some thing here.

**Comment by Watson1978** [comment]
Sorry for the very late reply, and thank you for the detailed report.

This turned out to be a bug in the `remote_syslog_sender` gem rather than in this plugin, and it has already been fixed upstream.

Your configuration was correct, and the plugin does pass `verify_mode 0` through to the sender as expected (`0` is truthy in Ruby, so `options[:verify_mode] = @verify_mode if @verify_mode` does set it). The problem is that `remote_syslog_sender` 1.2.1 ran the verification check unconditionally, regardless of `verify_mode`:

```ruby
# remote_syslog_sender 1.2.1 - lib/remote_syslog_sender/tcp_sender.rb
@socket = OpenSSL::SSL::SSLSocket.new(@tcp_socket, context)
@socket.connect
@socket.post_connection_check(@remote_hostname)
raise "verification error" if @socket.verify_result != OpenSSL::X509::V_OK
```

That `raise "verification error"` is exactly line 73 in your backtrace.

It was fixed in remote_syslog_sender 1.2.2 (released on 2021-07-07), which skips the check when verification is disabled:

```ruby
# remote_syslog_sender 1.2.2 and later
if @verify_mode != OpenSSL::SSL::VERIFY_NONE
  @socket.post_connection_check(@remote_hostname)
  raise "verification error" if @socket.verify_result != OpenSSL::X509::V_OK
end
```

So updating the gem should resolve the problem:

```
$ fluent-gem update remote_syslog_sender
```

For the record, `none` and `OpenSSL::SSL::VERIFY_NONE` produced the same error because `verify_mode` is declared as an `integer` parameter and Fluentd converts non-numeric strings with `String#to_i`, which yields `0` for both. In other words, all three of your attempts ended up as `verify_mode 0` and hit the same upstream bug.

That said, instead of disabling verification entirely, we would recommend pointing `ca_file` at your self-signed certificate so that the connection is still verified:

```
<match **>
  @type remote_syslog
  host "syslogserver"
  port 12555
  protocol tcp
  tls true
  ca_file /path/to/selfsigned.pem
  packet_size 65535
</match>
```


I am closing this issue as resolved upstream, but please feel free to reopen it if you still see the error with remote_syslog_sender 1.2.2 or later.
